name: IGSQ-Spigot
version: 0.1.6
softdepend: [LuckPerms]
depend: [ProtocolLib]
author: Murrobby
main: me.murrobby.igsq.spigot.Spigot
description: Custom Plugin Made For The Official IGSQ Server
api-version: 1.16

commands:
  igsq:
   aliases: [sq]
   description: Holds Every igsq command.
   