name: IGSQ-Spigot
version: 0.0.4
author: Murrobby
main: me.murrobby.igsq.Main_Spigot
description: Custom Plugin Made For The Official IGSQ Server
api-version: 1.16

commands:
  igsq:
   aliases: [sq]
   description: Holds Every igsq command.
   